/**
 * The caduceus mark, rendered from the shared pixel grid.
 *
 * Drawn as one SVG `<rect>` per filled cell with `shapeRendering="crispEdges"`,
 * so it stays perfectly sharp at any size and on any display scale — a scaled
 * bitmap would blur, and a smooth vector would lose the pixel-art character
 * entirely. Each part takes its fill from `PIXEL_FILL`, which routes the accent
 * snake through CSS variables; wings and staff use fixed colours from the icon art.
 *
 * The grid itself is generated by `scripts/make-icons.py`, which also produces
 * the app and menu-bar icons — so what floats on screen and what sits in the
 * Dock can never drift apart.
 */

import {
  CADUCEUS_HEIGHT,
  CADUCEUS_PIXELS,
  CADUCEUS_WIDTH,
  PIXEL_FILL,
} from "./caduceusPixels";

export function CaduceusMark({
  height,
  className,
  title,
}: {
  /** Rendered height in CSS pixels; width follows the grid's aspect ratio. */
  height: number;
  className?: string;
  title?: string;
}) {
  const width = Math.round((height * CADUCEUS_WIDTH) / CADUCEUS_HEIGHT);

  return (
    <svg
      width={width}
      height={height}
      viewBox={`0 0 ${CADUCEUS_WIDTH} ${CADUCEUS_HEIGHT}`}
      shapeRendering="crispEdges"
      className={className}
      role={title ? "img" : "presentation"}
      aria-label={title}
      aria-hidden={title ? undefined : true}
    >
      {title && <title>{title}</title>}
      {CADUCEUS_PIXELS.map(([x, y, kind]) => (
        <rect key={`${x}:${y}`} x={x} y={y} width={1} height={1} fill={PIXEL_FILL[kind]} />
      ))}
    </svg>
  );
}
