// GENERATED by scripts/make-icons.py — do not edit by hand.
//
// The caduceus mark as pixel data. The floating staff renders these as SVG
// rects, which keeps it crisp at any size and lets each part take its colour
// from a CSS variable — so the snakes pick up the user's accent. The raster app
// and tray icons come from the same grid, so the two can never drift apart.

export const CADUCEUS_WIDTH = 13;
export const CADUCEUS_HEIGHT = 20;

export type PixelKind = "knob" | "staff" | "wing" | "snakeA" | "snakeB";

/** `[x, y, kind]`, one entry per filled cell. */
export const CADUCEUS_PIXELS: readonly (readonly [number, number, PixelKind])[] = [
  [6, 0, "knob"],
  [5, 1, "knob"],
  [6, 1, "knob"],
  [7, 1, "knob"],
  [6, 2, "staff"],
  [0, 3, "wing"],
  [1, 3, "wing"],
  [2, 3, "wing"],
  [6, 3, "staff"],
  [10, 3, "wing"],
  [11, 3, "wing"],
  [12, 3, "wing"],
  [1, 4, "wing"],
  [2, 4, "wing"],
  [3, 4, "wing"],
  [4, 4, "wing"],
  [6, 4, "staff"],
  [8, 4, "wing"],
  [9, 4, "wing"],
  [10, 4, "wing"],
  [11, 4, "wing"],
  [3, 5, "wing"],
  [4, 5, "wing"],
  [5, 5, "wing"],
  [6, 5, "staff"],
  [7, 5, "wing"],
  [8, 5, "wing"],
  [9, 5, "wing"],
  [3, 6, "snakeB"],
  [4, 6, "snakeB"],
  [5, 6, "wing"],
  [6, 6, "staff"],
  [7, 6, "wing"],
  [8, 6, "snakeA"],
  [9, 6, "snakeA"],
  [4, 7, "snakeB"],
  [6, 7, "staff"],
  [8, 7, "snakeA"],
  [4, 8, "snakeB"],
  [6, 8, "staff"],
  [8, 8, "snakeA"],
  [5, 9, "snakeB"],
  [6, 9, "staff"],
  [7, 9, "snakeA"],
  [6, 10, "snakeA"],
  [5, 11, "snakeA"],
  [6, 11, "staff"],
  [7, 11, "snakeB"],
  [4, 12, "snakeA"],
  [6, 12, "staff"],
  [8, 12, "snakeB"],
  [4, 13, "snakeA"],
  [6, 13, "staff"],
  [8, 13, "snakeB"],
  [4, 14, "snakeA"],
  [6, 14, "staff"],
  [8, 14, "snakeB"],
  [5, 15, "snakeA"],
  [6, 15, "staff"],
  [7, 15, "snakeB"],
  [6, 16, "snakeB"],
  [5, 17, "snakeB"],
  [6, 17, "staff"],
  [7, 17, "snakeA"],
  [4, 18, "snakeB"],
  [6, 18, "staff"],
  [8, 18, "snakeA"],
  [6, 19, "staff"],
];

/**
 * Fill for each part. Wings stay fixed white (same as the app icons); the staff
 * keeps a warm gold; one snake follows the user's accent.
 */
export const PIXEL_FILL: Record<PixelKind, string> = {
  knob: "#ffe9a8",
  staff: "#e8c468",
  wing: "#ffffff",
  snakeA: "rgb(var(--c-accent))",
  snakeB: "#4fe3d0",
};
